import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer";
import Provider from "@/components/provider";
import InitialHeader from "@/components/InitialHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          {/* <InitialHeader /> */}
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
