import "./globals.css";
import { Inter } from "next/font/google";

import { getServerSession } from "next-auth/next";
import { authOptions } from "../app/api/auth/[...nextauth]/route";

import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Provider from "@/components/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <Header session={session} />
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
